[package]
name = "baca"
version = "0.1.0"
authors = ["Hubert Jaremko <hjaremko@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.3", features = ["yaml"] }
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
reqwest = { version = "0.11.2", features = ["blocking", "json", "cookies", "multipart"] }
dyn-fmt = "0.3.0"
colored = "2.0.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
zip = { version = "0.5.12", default-features = false }