name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-
      - name: Build project
        run: cargo build --verbose --all --all-targets
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: baca-${{ runner.os }}
          path: ./target/debug/baca*
      - name: Run tests
        run: cargo test --verbose
      - name: Add clippy
        run: rustup component add clippy
      - name: Run linter
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
          name: Clippy

#  coverage:
#    name: Code Coverage
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: nightly
#          override: true
#      - uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --all-features --no-fail-fast
#        env:
#          CARGO_INCREMENTAL: '0'
#          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
#          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
#      - uses: actions-rs/grcov@v0.1
#      - name: Coveralls upload
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: ${{ steps.coverage.outputs.report }}
